### PR TITLE
feat: Refactor mixins and improve their typing

### PR DESCRIPTION
**Pull request by mykola-mokhnach**

### CODE REVIEW

**Comment by KazuCocoa** [comment]
lg overall to me. I'm preparing a real device quick check on my local.

**Comment by KazuCocoa** [comment]
Not sure by this PR, but I got below error with this PR:
```
[RemoteDebugger] Attempting app 'PID:692'
[RemoteDebugger] Sending '_rpc_forwardGetListing:' message to app 'PID:692' (id: 4): 'connectToApp'
uncaughtException: Cannot read properties of undefined (reading 'debug')
TypeError: Cannot read properties of undefined (reading 'debug')
    at RpcMessageHandler.<anonymous> (/Users/kazu/github/appium-remote-debugger/lib/rpc/rpc-client.js:412:20)
    at Object.onceWrapper (node:events:628:26)
    at RpcMessageHandler.emit (node:events:525:35)
    at RpcMessageHandler.handleMessage (/Users/kazu/github/appium-remote-debugger/lib/rpc/rpc-message-handler.js:46:14)
    at RpcClientRealDevice.receive (/Users/kazu/github/appium-remote-debugger/lib/rpc/rpc-client-real-device.js:62:31)
    at PlistServiceDecoder.<anonymous> (/Users/kazu/github/appium-remote-debugger/node_modules/appium-ios-device/lib/webinspector/index.js:228:7)
    at PlistServiceDecoder.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at PlistServiceDecoder.Readable.push (node:internal/streams/readable:228:10)
    at PlistServiceDecoder._decode (/Users/kazu/github/appium-remote-debugger/node_modules/appium-ios-device/lib/plist-service/transformer/plist-service-decoder.js:27:10)
    at PlistServiceDecoder._transform (/Users/kazu/github/appium-remote-debugger/node_modules/appium-ios-device/lib/plist-service/transformer/plist-service-decoder.js:14:10)
    at PlistServiceDecoder.Transform._write (node:internal/streams/transform:205:23)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at PlistServiceDecoder.Writable.write (node:internal/streams/writable:336:10)
    at LengthBasedSplitter.ondata (node:internal/streams/readable:754:22)
    at LengthBasedSplitter.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at LengthBasedSplitter.Readable.push (node:internal/streams/readable:228:10)
    at LengthBasedSplitter._decode (/Users/kazu/github/appium-remote-debugger/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:69:10)
    at LengthBasedSplitter._transform (/Users/kazu/github/appium-remote-debugger/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:30:47)
    at LengthBasedSplitter.Transform._write (node:internal/streams/transform:205:23)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at LengthBasedSplitter.Writable.write (node:internal/streams/writable:336:10)
    at StreamLogger.ondata (node:internal/streams/readable:754:22)
```

This was part of new session request with `browserName: safari`

https://gist.github.com/KazuCocoa/cd236c127a6e1a4ba4802a12fd8749b6

Checking with current master

**Comment by KazuCocoa** [comment]
nvm, my local had a weird? commit

```
commit 384624426db9d848fd623c3aa9f34e0afa48b45b
```

current latest seems good.

**Review by KazuCocoa — APPROVED** [review]
lg

**Comment by mykola-mokhnach** [comment]
> nvm, my local had a weird? commit
> 
> ```
> commit 384624426db9d848fd623c3aa9f34e0afa48b45b
> ```
> 
> current latest seems good.

There was more to it, but I have reverted these changes to keep this PR smaller, which is easier to review.
the other changes could be a part of another PR.

**Pull request merged**
