### PR TITLE
ci: bump up ios versions, device, xcode and macos version under test

### PR DESCRIPTION
**Pull request by mwakizaka**
although I'm not familiar with GitHub actions, updated based on https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode

### CODE REVIEW

**Comment by mwakizaka** [comment]
will check later
```
 1) Safari remote debugger
       should be able to call 'selectApp' after already connecting to app:
     Error: No apps connected
      at /Users/runner/work/appium-remote-debugger/appium-remote-debugger/test/functional/safari-e2e-specs.js:109:13
      at async wrapped (node_modules/asyncbox/lib/asyncbox.js:93:13)
      at async retry (node_modules/asyncbox/lib/asyncbox.js:66:13)
      at async retryInterval (node_modules/asyncbox/lib/asyncbox.js:103:10)
      at async connect (test/functional/safari-e2e-specs.js:104:12)
      at async Context.<anonymous> (test/functional/safari-e2e-specs.js:214:5)

  2) Safari remote debugger
       should be able to get console logs from a remote page:
     TypeError: Cannot read properties of null (reading 'on')
      at /Users/runner/work/appium-remote-debugger/appium-remote-debugger/lib/rpc/rpc-client-simulator.js:134:19
      at Promise.cancellationExecute [as _execute] (node_modules/bluebird/js/release/debuggability.js:406:9)
      at Promise._resolveFromExecutor (node_modules/bluebird/js/release/promise.js:518:18)
      at new Promise (node_modules/bluebird/js/release/promise.js:103:10)
      at RpcClientSimulator.sendMessage (lib/rpc/rpc-client-simulator.js:124:18)
      at /Users/runner/work/appium-remote-debugger/appium-remote-debugger/lib/rpc/rpc-client.js:324:32
      at Promise.cancellationExecute [as _execute] (node_modules/bluebird/js/release/debuggability.js:406:9)
      at Promise._resolveFromExecutor (node_modules/bluebird/js/release/promise.js:518:18)
      at new Promise (node_modules/bluebird/js/release/promise.js:103:10)
      at RpcClientSimulator.sendToDevice (lib/rpc/rpc-client.js:234:18)
      at RpcClientSimulator.send (lib/rpc/rpc-client.js:204:25)
      at RemoteDebugger.setConnectionKey (lib/mixins/connect.js:44:24)
      at /Users/runner/work/appium-remote-debugger/appium-remote-debugger/test/functional/safari-e2e-specs.js:108:16
      at wrapped (node_modules/asyncbox/lib/asyncbox.js:93:19)
      at retry (node_modules/asyncbox/lib/asyncbox.js:66:19)
      at async retryInterval (node_modules/asyncbox/lib/asyncbox.js:103:10)
      at async connect (test/functional/safari-e2e-specs.js:104:12)
      at async Context.<anonymous> (test/functional/safari-e2e-specs.js:227:5)



Error: Process completed with exit code 2.
```

**Review by mykola-mokhnach — APPROVED** [review]
We usually add `ci:` prefix to such PRs

**Comment by mwakizaka** [comment]
finally passed 🎉

**Comment by mwakizaka** [comment]
@mykola-mokhnach @KazuCocoa 
Excuse me, may I ask you to check this PR?

**Review by mykola-mokhnach — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
Thanks for working on it @mwakizaka 
Feel free to ping us anytime regarding reviews in the Appium Slack channel (or provide your email address if you are still not there)

**Comment by mwakizaka** [comment]
> Thanks for working on it @mwakizaka Feel free to ping us anytime regarding reviews in the Appium Slack channel (or provide your email address if you are still not there)

Thank you! Please use mwakizaka0108@gmail.com

**Pull request merged**
