### PR TITLE
fix: Only try to select Safari if it is enabled for automation

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Safari does not return any pages if it is not available for automation

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Do you think it makes sense to enable this condition for any web views or it is only applicable to Safari only?

**Comment by KazuCocoa** [comment]
Let me check a bit carefully with some combinations. I think the true/false conditions themselves should be the same for both Safari/WebView, but I need to double check the Ui Automation and the WebInspector config in the settings app. 

UI Automation in Safari settings may not affect the remote debugger (WebInspector) usage but Web Inspector affects it.

**Comment by KazuCocoa** [comment]
```
[debug] [RemoteDebugger] Selecting application
[debug] [RemoteDebugger] Current applications available:
[debug] [RemoteDebugger]     Application: "PID:726"
[debug] [RemoteDebugger]         id: "PID:726"
[debug] [RemoteDebugger]         isProxy: false
[debug] [RemoteDebugger]         name: "amsengagementd"
[debug] [RemoteDebugger]         bundleId: "com.apple.amsengagementd"
[debug] [RemoteDebugger]         hostId: undefined
[debug] [RemoteDebugger]         isActive: false
[debug] [RemoteDebugger]         isAutomationEnabled: "Unknown"
[debug] [RemoteDebugger]     Application: "PID:1046"
[debug] [RemoteDebugger]         id: "PID:1046"
[debug] [RemoteDebugger]         isProxy: false
[debug] [RemoteDebugger]         name: "Safari"
[debug] [RemoteDebugger]         bundleId: "com.apple.mobilesafari"
[debug] [RemoteDebugger]         hostId: undefined
[debug] [RemoteDebugger]         isActive: true
[debug] [RemoteDebugger]         isAutomationEnabled: "Unknown"
[debug] [RemoteDebugger]     Application: "PID:298"
[debug] [RemoteDebugger]         id: "PID:298"
[debug] [RemoteDebugger]         isProxy: false
[debug] [RemoteDebugger]         name: "HeuristicInterpreter"
[debug] [RemoteDebugger]         bundleId: "process-HeuristicInterpreter"
[debug] [RemoteDebugger]         hostId: undefined
[debug] [RemoteDebugger]         isActive: false
[debug] [RemoteDebugger]         isAutomationEnabled: "Unknown"
[debug] [RemoteDebugger] Checking for bundle identifiers: com.apple.WebKit.WebContent, process-com.apple.WebKit.WebContent, process-SafariViewService, com.apple.SafariViewService, *, com.apple.mobilesafari
[debug] [RemoteDebugger] Found app id key 'PID:1046' for bundle 'com.apple.mobilesafari'
[debug] [RemoteDebugger] Trying out the possible app ids: PID:1046 (try #1 of 10)
```

Just a note: as https://github.com/mykola-mokhnach/appium-remote-debugger/blob/e959dbb66aed40a97955b241227acf4019a6a6f9/lib/utils.js#L66-L67, we have a case isAutomationEnable is configured as "Unknown". It is a valid value for automation via Web Inspector.

**Comment by KazuCocoa** [comment]
Another note for a webview app (uikitcatalog):

`isInspectable` was false:
```
[debug] [RemoteDebugger]     Application: "PID:1209"
[debug] [RemoteDebugger]         id: "PID:1209"
[debug] [RemoteDebugger]         isProxy: false
[debug] [RemoteDebugger]         name: "UIKitCatalog"
[debug] [RemoteDebugger]         bundleId: "com.kazucocoa.apple-samplecode.UICatalog"
[debug] [RemoteDebugger]         hostId: undefined
[debug] [RemoteDebugger]         isActive: true
[debug] [RemoteDebugger]         isAutomationEnabled: "Unknown"
[debug] [RemoteDebugger] Checking for bundle identifiers: com.apple.WebKit.WebContent, process-com.apple.WebKit.WebContent, process-SafariViewService, com.apple.SafariViewService, *, com.kazucocoa.apple-samplecode.UICatalog
[debug] [RemoteDebugger] Found app id key 'PID:1209' for bundle 'com.kazucocoa.apple-samplecode.UICatalog'
[debug] [RemoteDebugger] Trying out the possible app ids: PID:1209 (try #20 of 20)
[debug] [RemoteDebugger] Attempting app 'PID:1209'
[debug] [RemoteDebugger] Sending '_rpc_forwardGetListing:' message to app 'PID:1209' (id: 58): 'connectToApp'
[debug] [ios-device] Sent message to Web Inspector:
[debug] [ios-device] {
  "__argument": {
    "WIRConnectionIdentifierKey": "af249c12-b1bb-411a-9ee4-d5e1a62452e9",
    "WIRApplicationIdentifierKey": "PID:1209"
  },
  "__selector": "_rpc_forwardGetListing:"
}
[debug] [ios-device] Received message from Web Inspector:
[debug] [ios-device] {
  "__argument": {
    "WIRApplicationIdentifierKey": "PID:1209",
    "WIRListingKey": {}
  },
  "__selector": "_rpc_applicationSentListing:"
}
[debug] [RemoteDebugger] Received response from send (id: 58): '["PID:1209",{}]'
[debug] [RemoteDebugger] Sending to Web Inspector took 6ms
[debug] [RemoteDebugger] Error: Empty page dictionary received
    at /Users/kazu/GitHub/appium-remote-debugger/lib/rpc/rpc-client.js:757:20
[RemoteDebugger] Error checking application PID:1209: 'Empty page dictionary received'
```


`isInspectable` was true:
```
[debug] [RemoteDebugger] Sending '_rpc_forwardGetListing:' message to app 'PID:1215' (id: 2): 'connectToApp'
[debug] [ios-device] Sent message to Web Inspector:
[debug] [ios-device] {
  "__argument": {
    "WIRConnectionIdentifierKey": "ba4b9e99-7e91-4077-9864-a0dcdc187aba",
    "WIRApplicationIdentifierKey": "PID:1215"
  },
  "__selector": "_rpc_forwardGetListing:"
}
[debug] [ios-device] Received message from Web Inspector:
[debug] [ios-device] {
  "__argument": {
    "WIRApplicationIdentifierKey": "PID:1215",
    "WIRListingKey": {
      "1": {
        "WIRTitleKey": "WKWebView",
        "WIRTypeKey": "WIRTypeWebPage",
        "WIRURLKey": "file:///private/var/containers/Bundle/Application/3D4087F5-61AA-48C3-B225-DE28DCE44979/UIKitCatalog.app/Base.lproj/content.html",
        "WIRPageIdentifierKey": 1,
        "WIRHostApplicationIdentifierKey": "PID:1215",
        "WIROverrideNameKey": ""
      }
    }
  },
  "__selector": "_rpc_applicationSentListing:"
}
[debug] [RemoteDebugger] Received response from send (id: 2): '["PID:1215",{"1":{"WIRTitleKey":"WKWebView","WIRTypeKey":"WIRTypeWebPage","WIRURLKey":"file:///private/var/containers/Bundle/Application/3D4087F5-61AA-48C3-B225-DE28DCE44979/UIKitCatalog.app/Base.l...'
````

So, based on a couple of combinations, I think no much diff between Safari and WebView app in terms of properties like `isAutomationEnabled`

**Pull request merged**
